/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'smallpigex' at '7/22/17 12:48 AM' with Gradle 2.14.1
 *
 * @author smallpigex, @date 7/22/17 12:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
